version: '3.9'

services:
  db:
    image: mariadb:$MARIADB_TAG
    container_name: '${PROJECT_NAME}_db'
    stop_grace_period: 30s
    restart: always
    environment:
      TZ: 'Europe/Kiev'
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_USER: $DB_ROOT_USER
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    ports:
      - '1229:3306'
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  bot:
    build:
      context: ./
      args:
        PYTHON_TAG: $PYTHON_TAG
    container_name: '${PROJECT_NAME}_bot'
    restart: always
    environment:
      TOKEN: $TOKEN
      API_IP: $API_IP
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      ADMIN_ID: $ADMIN_ID
    volumes:
      - ./:/usr/src/app:cached
    depends_on:
      - db

  adminer:
    container_name: '${PROJECT_NAME}_adminer'
    image: adminer:$ADMINER_TAG
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
      ADMINER_DEFAULT_DB_DRIVER: server
    ports:
      - '8080:8080'
    depends_on:
      - db
      #  nginx:
      #    image: wodby/nginx:$NGINX_TAG
      #    container_name: "${PROJECT_NAME}_nginx"
      #    depends_on:
      #      - python
      #    environment:
      #      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      #      NGINX_ERROR_LOG_LEVEL: debug
      #      NGINX_VHOST_PRESET: django
      #      NGINX_BACKEND_HOST: python
      # Use this if you don't need Django's media/static locations.
      #NGINX_VHOST_PRESET: http-proxy
      #    volumes:
      #      - ./:/usr/src/app:cached
      ## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/python/local#docker-for-mac
      #    - backend:/usr/src/app
      #    labels:
      #    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
